apt:
  install:
    - autojump
    - btop
    - dconf-editor
    - fzf
    - gnome-tweaks
    - htop
    - ripgrep
    - snapd
    - thefuck
    - tlp
    - tmux
    - tree
    - vim
    - yubikey-manager-qt
    - solaar
    - silversearcher-ag
    - lm-sensors
    - hardinfo
    - inxi
    - stress
  # remove:
  install_laptop:
    - fprintd  # Fingerprint - laptop only 
    - libpam-fprintd # Fingerprint - laptop only
    - bat # battery




