---
- hosts: all
  remote_user: root

  # roles:
  #   - role: diodonfrost.jetbrains_toolbox
  #     become: true
  #     vars:
  #       jetbrains_toolbox_version: "latest"  
  #       jetbrains_tools_to_install: ["pycharm-community"]
        
  tasks:
  #   - include_tasks: roles/packages/tasks/main.yml
  #     tags: packages
  # #   # Include tasks for configuring Zsh shell
  #   - include_tasks: roles/zsh/tasks/main.yml
  #     tags: zsh
    - include_tasks: roles/thinkfan/tasks/main.yml
      tags: thinkfan
          
        
        

