---
# Default variables for nas-mount role
nas_server: nas.local
nas_fs_type: cifs
nas_credentials_file: /etc/cifs-credentials

# List of NAS mounts to configure
nas_mounts:
  - share: personal_folder
    mount_point: lee
  - share: share
    mount_point: share
  - share: backups
    mount_point: backups
  - share: lee_data
    mount_point: lee_data
  - share: max_share
    mount_point: max_share

# Package requirements
required_packages:
  - cifs-utils